name: Test
on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Cache pip dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: cache-0
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Cache poetry dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: cache-{{ hashFiles('**/poetry.lock') }}
      - name: Install project dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
          INVALID_EMAIL: ${{ secrets.INVALID_EMAIL }}
          INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
          DEFAULT_WAIT_TIME: ${{ secrets.DEFAULT_WAIT_TIME }}
      - name: Upload GH Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: htmlcov
  deploy:
    needs: test
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GH Pages
        uses: actions/deploy-pages@v1
